# Tap external Homebrew Cask repositories.
homebrew_cask_repositories:
  - caskroom/versions
  - caskroom/fonts

# Managed Homebrew Cask packages.
#
# e.g.
# - package_name
# or
# { name: package_name, state: package_state }
#
# state choices: [present, absent, installed, uninstalled] (default: present)
homebrew_cask_packages:
  - 1password
  - xquartz
  - java
  - alfred
  - astah-community
  - atom
  - cgoban
  - clipmenu
  - cuda
  - dockertoolbox
  - font-fira-code
  - flux
  - gimp
  - google-chrome
  - google-cloud-sdk
  - google-japanese-ime
  - intellij-idea-ce
  - iterm2
  - java6
  - karabiner
  - latexit
  - night-owl
  - macdown
  - mactex
  - macvim
  - mendeley-desktop
  - mysqlworkbench
  - packer
  - pycharm-ce
  - rstudio
  - seil
  - sequel-pro
  - skitch
  - skype
  - sqlitebrowser
  - sublime-text3
  - virtualbox
  - vagrant

# other useful app not contained in cask or not recommended to install by cask

# gifbrewery
# ipmessenger
# microsoft remote desktop
# wunderlist
# cinch
# cmdQuit
# pasteasy
# browseshot
# slack
