# Tap external Homebrew repositories.
#
# e.g.
# - homebrew/binary
homebrew_repositories:
  - homebrew/binary
  - homebrew/science
  - homebrew/boneyard
  - staticfloat/julia
  - neovim/neovim

# Managed Homebrew packages.
#
# e.g.
# - package_name
# or
# { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
#
# state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
# install_options: string or sequence (default: none)
homebrew_packages:
  - gcc
  - vim
  - neovim
  - { name: openssl, state: linked, install_options: force }
  - ansible
  - git
  - git-flow
  - apache-spark
  - bazel
  - boot2docker
  - cabal-install
  - chrome-cli
  - coreutils
  - cmake
  - curl
  - digdag
  - docker
  - docker-machine
  - doxygen
  - elixir
  - erlang
  - fontconfig
  - freetype
  - ghc
  - ghostscript
  - gibo
  - git-flow
  - git-lfs
  - glib
  - go
  - graphviz
  - haskell-stack
  - hadoop
  - hub
  - imagemagick
  - jenkins
  - jq
  - jpeg
  - julia
  - libssh2
  - llvm
  - maven
  - mahout
  - mecab
  - mecab-ipadic
  - mercurial
  - midnight-commander
  - mycli
  - mysql
  - nkf
  - nginx
  - nmap
  - node
  - nvm
  - openblas
  - opencv
  - openssl
  - pango
  - pdf2svg
  - peco
  - pgcli
  - postgresql
  - phantomjs
  - pyenv
  - pyenv-virtualenv
  - python
  - python3
  - R
  - redis
  - ruby-build
  - rust
  - rbenv
  - sbt
  - scala
  - sqlite
  - tailor
  - tig
  - tmux
  - tree
  - the_silver_searcher
  - typesafe-activator
  - w3m
  - watch
  - watchman
  - wget
  - wireshark
  - wine
  - xz
  - vim
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting

# tool for developing mobile app
# xcproj
# xctool

# app for hobby
# simutrans
